chore(tsconfig): enable skipLibCheck to circumvent problems in ical.js
Is not critical as the upstream typing information is based on their
Jsdoc anyway. They are not using TypeScript so it doesn't make sense to
be overly strict here.

```
node_modules/ical.js/dist/types/vcard_time.d.ts:51:5 - error TS2610: 'icaltype' is defined as an accessor in class 'Time', but is overridden here in 'VCardTime' as an instance property.

51     icaltype: string;
       ~~~~~~~~
```

Signed-off-by: Richard Steinmetz <richard@steinmetz.cloud>